<?php

/**
 * Words kept out of case keys (scripts/case-key-words/build.php).
 *
 * contains: any word with this inside it is dropped, so "rape" also drops
 *           grape and drape. Losing harmless words costs a little entropy;
 *           showing a survivor a word that echoes what happened costs more.
 * prefix:   any word starting with this.
 * exact:    only this word, where a stem would catch too much ("war" would
 *           drop warm and award).
 */
return [
    'contains' => [
        // violence, crime and harm
        'abduct', 'abus', 'assault', 'attack', 'batter', 'beat', 'bleed', 'blood', 'bludgeon', 'bomb',
        'bruis', 'brutal', 'bull', 'burglar', 'butcher', 'captiv', 'casualt', 'chok', 'clobber', 'coffin',
        'combat', 'corpse', 'crime', 'crimin', 'cruel', 'crush', 'dagger', 'danger', 'dead', 'death',
        'decay', 'defil', 'drown', 'dungeon', 'enemy', 'evil', 'execut', 'explod', 'explos', 'fatal',
        'fight', 'firearm', 'flog', 'fright', 'funeral', 'gash', 'gore', 'grave', 'grief', 'griev',
        'grope', 'gun', 'harass', 'hatred', 'haunt', 'hostage', 'hurt', 'injur', 'kidnap', 'kill',
        'knife', 'knives', 'lethal', 'lynch', 'maim', 'malic', 'manhandl', 'massacre', 'menac', 'molest',
        'morgue', 'murder', 'nightmare', 'pain', 'panic', 'poison', 'predator', 'prey', 'prison', 'punch',
        'punish', 'rape', 'ravag', 'revenge', 'riot', 'robber', 'scar', 'scream', 'shoot', 'slash',
        'slaughter', 'slay', 'smother', 'sniper', 'stab', 'stalk', 'strangl', 'struggl', 'suffer', 'suicid',
        'terror', 'threat', 'thug', 'torment', 'tortur', 'trauma', 'trap', 'unsafe', 'venom', 'victim',
        'violat', 'violen', 'weapon', 'whip', 'wound', 'wreck', 'force', 'grab', 'pinned', 'restrain',
        'hostil', 'bully', 'brawl', 'clash', 'bloody', 'hang', 'noose', 'cuff', 'handcuff', 'gag',
        'bind', 'bound', 'bandit', 'pirate', 'hijack', 'mug', 'loot', 'ransack', 'steal', 'stole',
        'thief', 'theft', 'crook', 'outlaw', 'felon', 'convict', 'jail', 'arrest', 'police', 'cop',
        'sheriff', 'detective', 'suspect', 'accus', 'guilt', 'testif', 'witness', 'lawsuit', 'trial',
        'verdict', 'sentenc', 'penal', 'warden', 'swat', 'sting', 'raid', 'ambush', 'invad', 'invasion',
        'siege', 'soldier', 'battle', 'missile', 'rifle', 'pistol', 'bullet', 'ammo', 'cannon', 'grenade',
        'sword', 'spear', 'arrow', 'axe', 'hatchet', 'machete', 'blade', 'razor', 'scalpel', 'syringe',
        'needle', 'chainsaw', 'mace', 'taser', 'stun', 'zap', 'shove', 'slap', 'smack', 'spank', 'kick',
        'stomp', 'trample', 'bite', 'claw', 'scratch', 'pinch', 'squeez', 'bash', 'hammer', 'pound',
        'thump', 'wallop', 'whack', 'clamp', 'hunt', 'trapp', 'snare', 'lure', 'stray', 'creep',
        'lurk', 'spy', 'peep', 'snoop', 'voyeur', 'expos', 'flash', 'chase', 'flee', 'fled', 'escape',
        'hide', 'hiding', 'cower', 'tremb', 'shiver', 'shudder', 'quiver', 'shaking', 'shaken', 'shook',
        'blackmail', 'extort', 'coerc', 'manipul', 'deceiv', 'decept', 'betray', 'trick', 'drag',
        'yank', 'jerk', 'thrash', 'flail', 'wrestl', 'tackl', 'pummel', 'maul', 'mangl', 'mutilat',
        'cripple', 'disfigur', 'deform', 'sever', 'amputat', 'fractur', 'broken', 'shatter',
        // sex and the body
        'abdom', 'anatom', 'armpit', 'bikini', 'bladder', 'bosom', 'breast', 'buttock', 'cleavage',
        'crotch', 'cuddl', 'flirt', 'groin', 'intimat', 'kiss', 'lingerie', 'lust', 'naked', 'navel',
        'nipple', 'nude', 'nudis', 'nudit', 'orgasm', 'pelvi', 'porn', 'sensual', 'sex', 'spouse',
        'strip', 'thigh', 'topless', 'undress', 'unzip', 'virgin', 'womb', 'zipper', 'bedroom',
        'bed', 'mattress', 'pillow', 'blanket', 'sheet', 'pajama', 'underwear', 'panties', 'bra',
        'boxer', 'brief', 'garter', 'corset', 'thong', 'skin', 'flesh', 'body', 'bodies', 'torso',
        'chest', 'belly', 'hip', 'lip', 'mouth', 'tongue', 'throat', 'neck', 'waist', 'leg', 'thumb',
        'finger', 'hand', 'fist', 'palm', 'wrist', 'elbow', 'knee', 'ankle', 'foot', 'feet', 'toe',
        'hair', 'scalp', 'skull', 'bone', 'spine', 'rib', 'lung', 'liver', 'kidney', 'heart', 'gland',
        'organ', 'tissue', 'muscle', 'vein', 'artery', 'pulse', 'sweat', 'saliva', 'spit', 'drool',
        'tear', 'cry', 'sob', 'weep', 'wail', 'moan', 'groan', 'whimper', 'gasp', 'pant', 'breath',
        'lick', 'suck', 'swallow', 'gulp', 'chew', 'touch', 'caress', 'fondl', 'grop', 'rub', 'stroke',
        'massag', 'embrace', 'hug', 'snuggl', 'nuzzl', 'tickl', 'seduc', 'tempt', 'desire', 'crave',
        'passion', 'romance', 'romantic', 'lover', 'darling', 'honey', 'sweetie', 'babe', 'baby',
        'date', 'dating', 'boyfriend', 'girlfriend', 'husband', 'wife', 'marri', 'wedding', 'bride',
        'groom', 'divorc', 'pregnan', 'birth', 'fetus', 'diaper', 'nurse', 'breed', 'mate', 'mating',
        // drink, drugs, illness and medicine
        'alcohol', 'beer', 'booze', 'drink', 'drunk', 'hangover', 'liquor', 'tipsy', 'vodka', 'whisk',
        'wine', 'cocktail', 'intoxic', 'sedat', 'drug', 'dose', 'overdos', 'pill', 'tablet', 'opium',
        'narcot', 'cocaine', 'heroin', 'stoned', 'dizzy', 'drowsy', 'faint', 'unconscious', 'numb',
        'blackout', 'pass out', 'ambulance', 'autopsy', 'coma', 'disease', 'hospital', 'illness', 'infect',
        'nausea', 'sick', 'surgery', 'surgical', 'toxic', 'vomit', 'fever', 'virus', 'germ', 'plague',
        'rash', 'wart', 'boil', 'blister', 'ulcer', 'tumor', 'cancer', 'stroke', 'seizure', 'clinic',
        'patient', 'medic', 'doctor', 'therap', 'exam', 'pregnancy', 'bandage', 'stitch', 'splint',
        'cast', 'crutch', 'scab', 'pus', 'mucus', 'phlegm', 'urin', 'feces', 'poop', 'pee', 'flush',
        'toilet', 'bath', 'shower', 'tub',
        // shame, fear, blame and grief
        'ashamed', 'blame', 'coward', 'crazy', 'dirty', 'disgrac', 'dumb', 'filth', 'foolish',
        'humiliat', 'idiot', 'insan', 'lunatic', 'shame', 'slut', 'stupid', 'ugly', 'whore',
        'worthless', 'liar', 'lying', 'fake', 'alone', 'lonel', 'sorrow', 'mourn', 'regret', 'scared',
        'afraid', 'anxious', 'anxiet', 'worri', 'worry', 'upset', 'helpless', 'hopeless', 'pity',
        'miser', 'gloom', 'despair', 'dread', 'fear', 'horror', 'horrif', 'terrif', 'awful', 'shock',
        'stress', 'distress', 'angry', 'anger', 'rage', 'furious', 'fury', 'hate', 'hating', 'spite',
        'bitter', 'jealous', 'envy', 'resent', 'agony', 'anguish', 'ache', 'aching', 'sore', 'sting',
        'burn', 'scald', 'scorch', 'singe', 'freez', 'frozen', 'drown', 'sink', 'sunk', 'doom',
        'curse', 'damn', 'hell', 'demon', 'devil', 'satan', 'ghoul', 'zombie', 'vampire', 'monster',
        'beast', 'brute', 'savage', 'wicked', 'sinister', 'vile', 'nasty', 'gross', 'disgust', 'repuls',
        'sicken', 'creepy', 'eerie', 'grim', 'morbid', 'macabre', 'ominous', 'scary', 'spook',
        'loser', 'failure', 'reject', 'deny', 'denial', 'silenc', 'hush', 'secret', 'conceal', 'cover',
        'gossip', 'rumor', 'slander', 'insult', 'mock', 'tease', 'taunt', 'ridicul', 'bully',
        'pressur', 'oppress', 'dominat', 'submiss', 'obey', 'slave', 'servant', 'master', 'owner',
        // places and things that can carry the moment back
        'frat', 'party', 'parties', 'dorm', 'campus', 'college', 'school', 'tuition', 'locker',
        'basement', 'cellar', 'closet', 'alley', 'van', 'trunk', 'cage', 'chain', 'rope', 'tape',
        'lock', 'bolt', 'latch', 'door', 'window', 'curtain', 'blind', 'dark', 'night', 'midnight',
        'camera', 'photo', 'video', 'film', 'record', 'phone', 'text', 'message', 'email', 'selfie',
    ],

    'prefix' => [
        'un', 'dis', 'mis',
    ],

    // Added after reading every word the rules above let through, by category.
    'reviewed' => [
        // body and medicine
        'achiness', 'afflicted', 'aids', 'amniotic', 'aneurism', 'antacid', 'aorta', 'appendage', 'aspirin',
        'atrophy', 'bloated', 'bloating', 'bony', 'bronchial', 'bunion', 'cardiac', 'cesarean', 'cheek',
        'chemo', 'chubby', 'clavicle', 'congested', 'contusion', 'cornea', 'coronary', 'cramp', 'cranial',
        'cranium', 'curvy', 'dandruff', 'diabetes', 'diabetic', 'diagnoses', 'diagnosis', 'diaphragm',
        'dimple', 'dorsal', 'dosage', 'eardrum', 'earlobe', 'embolism', 'endocrine', 'endorphin', 'epidemic',
        'epidermal', 'epidermis', 'epidural', 'esophagus', 'estrogen', 'excretion', 'excretory', 'facial',
        'femur', 'fetal', 'follicle', 'freckled', 'freckles', 'gangrene', 'gauze', 'geriatric', 'gestate',
        'gestation', 'gizzard', 'gonad', 'gout', 'hefty', 'ibuprofen', 'impaired', 'jaundice', 'jawed',
        'jawless', 'jawline', 'jaws', 'jugular', 'lanky', 'lankiness', 'laxative', 'ligament', 'limb',
        'mammary', 'molar', 'muscular', 'mumps', 'nape', 'nebulizer', 'neurology', 'ointment', 'outbreak',
        'ovary', 'pancreas', 'pandemic', 'pediatric', 'petite', 'polio', 'portly', 'pox', 'prenatal',
        'prognosis', 'pulmonary', 'retinal', 'scrawny', 'septic', 'septum', 'serotonin', 'skeletal',
        'skeleton', 'spinal', 'spleen', 'sprain', 'sterile', 'sterility', 'sterilize', 'sternum', 'strep',
        'swab', 'symptom', 'syndrome', 'tibia', 'triage', 'triceps', 'trimester', 'tummy', 'udder',
        'umbilical', 'urologist', 'urology', 'vascular', 'ventricle', 'vertigo', 'zit', 'specimen',
        'evidence', 'probe', 'probing', 'immunize', 'paralyses', 'paralysis', 'paralyze', 'stimulant',
        'washroom',
        // clothing that is underwear or close to it
        'blouse', 'bloomers', 'bootie', 'camisole', 'corsage', 'girdle', 'knickers', 'leotard', 'negligee',
        'petticoat', 'skirt', 'swimsuit', 'swimwear', 'shorts',
        // sex, desire and romance
        'affair', 'arousal', 'bust', 'catcall', 'cathouse', 'celibacy', 'celibate', 'chaste', 'chastity',
        'clubbing', 'douche', 'elope', 'engorge', 'enticing', 'exes', 'explicit', 'flaccid', 'frigidity',
        'frigidly', 'gigolo', 'hardcore', 'humped', 'humpback', 'immodest', 'impotence', 'impotency',
        'impotent', 'juicy', 'lubricant', 'lubricate', 'manhood', 'marital', 'matrimony', 'monogamy',
        'nuptials', 'ogle', 'procreate', 'procurer', 'prude', 'prudishly', 'purity', 'puritan',
        'ravishing', 'reproduce', 'sensuous', 'shaft', 'shank', 'showgirl', 'skimpily', 'slinky',
        'smitten', 'squirt', 'stiffen', 'stimulate', 'suitor', 'swinger', 'swooned', 'throbbing', 'tingle',
        'tingling', 'tingly', 'vaseline', 'wooing', 'dowry', 'pawing', 'pucker', 'slurp', 'progeny',
        'paternity', 'spousal', 'surrogate', 'feminine', 'feminize', 'masculine', 'mannish', 'manliness',
        'womanhood', 'womankind', 'womanless', 'womanlike', 'womanly', 'kinswoman', 'ladies', 'ladylike',
        'gents', 'gentleman', 'gender', 'bunny', 'kitty', 'busty',
        // consent, force and pressure
        'consent', 'willing', 'willfully', 'wanted', 'wanting', 'refusal', 'refuse', 'refusing', 'yield',
        'surrender', 'subdued', 'subduing', 'overpower', 'overthrow', 'onslaught', 'compel', 'comply',
        'obligate', 'obliged', 'persuaded', 'persuader', 'provoke', 'provoking', 'duress', 'confined',
        'confining', 'constrain', 'constrict', 'entangled', 'suffocate', 'stifle', 'stifling', 'throttle',
        'quiet', 'silent', 'secrecy', 'secluded', 'secluding', 'seclusion', 'safehouse', 'prone',
        'repressed', 'muzzle', 'mute', 'jab', 'lash', 'lasso', 'hurled', 'hurler', 'hurling', 'slam',
        'smasher', 'smashing', 'smashup', 'smite', 'slain', 'slit', 'impale', 'carnage', 'landmine',
        'detonate', 'detonator', 'bazooka', 'buckshot', 'shrapnel', 'revolver', 'turret', 'skirmish',
        'marauding', 'mutiny', 'plunder', 'poach', 'prowler', 'prowling', 'sneak', 'spied', 'onlooker',
        'wince', 'wincing', 'flinch', 'cringe', 'cringing', 'recoil', 'tremor', 'yelling', 'yelp',
        'shriek', 'grunt', 'pried', 'pry', 'hazing', 'curfew', 'survivor', 'survival', 'surviving',
        'survive', 'statute', 'statutory', 'ruined', 'tainted', 'trouble', 'troubling', 'turmoil',
        'upheaval', 'uproar', 'outburst', 'tantrum', 'raging', 'ranting', 'rants', 'wrath', 'vengeful',
        'vendetta', 'retaliate', 'abnormal',
        // sleep, drink and drugs
        'absinthe', 'amaretto', 'asleep', 'bartender', 'barmaid', 'barman', 'barstool', 'boozy', 'brewery',
        'brewing', 'cannabis', 'catnap', 'coke', 'doze', 'drank', 'drowsily', 'freebase', 'groggily',
        'groggy', 'junkie', 'liqueur', 'margarita', 'moonshine', 'morphine', 'napped', 'napping', 'nappy',
        'nicotine', 'oversleep', 'prozac', 'ritalin', 'saloon', 'schnapps', 'scotch', 'sherry', 'shindig',
        'siesta', 'sleep', 'slept', 'snooze', 'snore', 'snoring', 'spirits', 'spree', 'stupor', 'tavern',
        'trance', 'valium', 'woozy', 'delirious', 'delirium', 'oblivion', 'oblivious', 'joyride', 'cabbie',
        'cabdriver',
        // death and the macabre
        'afterlife', 'aftermath', 'calamity', 'casket', 'catacomb', 'coroner', 'deceased', 'decompose',
        'demise', 'entomb', 'exhume', 'gallows', 'gory', 'gorged', 'headstone', 'headsman', 'mortality',
        'mortally', 'mortician', 'mortuary', 'mummified', 'mummify', 'obituary', 'perish', 'reburial',
        'rotten', 'rotting', 'mayday', 'emergency', 'helpline', 'evacuate', 'evacuee', 'hazard',
        'pentagram', 'occultist', 'exorcism', 'exorcist', 'boogeyman', 'boogieman', 'phantom', 'banshee',
        // law, crime and school discipline
        'affidavit', 'alibi', 'apprehend', 'arson', 'cheating', 'confess', 'culpable', 'culprit', 'custody',
        'deceit', 'defame', 'defendant', 'defraud', 'detention', 'devious', 'embezzle', 'espionage',
        'evict', 'expel', 'expulsion', 'extradite', 'falsify', 'false', 'frisk', 'henchman', 'impeach',
        'judge', 'judicial', 'judiciary', 'juror', 'jury', 'justice', 'liability', 'liable', 'litigate',
        'litigator', 'mobster', 'parole', 'patrol', 'perjurer', 'perjury', 'persecute', 'precinct',
        'probation', 'reprimand', 'repossess', 'sabotage', 'scam', 'scandal', 'scapegoat', 'scoundrel',
        'shoplift', 'snitch', 'suing', 'tamper', 'tattle', 'tattling', 'thieving', 'thievish', 'traitor',
        'treason', 'trespass', 'villain', 'wrongdoer', 'wronged', 'wrongful', 'wrongly', 'wrongness',
        'goon', 'stooge', 'renegade', 'tabloid', 'paparazzi', 'polygraph', 'dropout', 'alumni', 'graduate',
        'semester', 'yearbook', 'varsity', 'registrar', 'residence', 'residency', 'resident', 'stadium',
        'nanny', 'sitter', 'grandma', 'grandpa', 'granddad', 'grandson', 'grandkid', 'granny', 'mama',
        'childcare', 'childhood', 'childish', 'childless', 'childlike', 'preteen', 'landlord', 'landlady',
        // shame, insult and mental health
        'autism', 'autistic', 'blaming', 'catatonic', 'chump', 'crazed', 'crazily', 'craziness', 'degraded',
        'degrading', 'dejected', 'demeaning', 'depraved', 'depravity', 'depress', 'deranged', 'desolate',
        'despise', 'destitute', 'detest', 'deviancy', 'deviant', 'dork', 'dweeb', 'dyslexia', 'dyslexic',
        'egomaniac', 'emptiness', 'epilepsy', 'epileptic', 'feeble', 'fool', 'gullible', 'hypocrisy',
        'hypocrite', 'idiocy', 'imbecile', 'immorally', 'impure', 'impurity', 'irate', 'isolated',
        'isolating', 'isolation', 'lunacy', 'mortified', 'mortify', 'neurosis', 'neurotic', 'nutcase',
        'oaf', 'phobia', 'pester', 'phony', 'profane', 'profanity', 'pyromania', 'rabid', 'recluse',
        'reclusive', 'remorse', 'repugnant', 'sadden', 'scolding', 'scorn', 'scowling', 'sinner', 'snide',
        'sneer', 'squeamish', 'stank', 'stench', 'stinking', 'stinky', 'strained', 'straining', 'sullen',
        'twerp', 'twisted', 'uptight', 'uselessly', 'wannabe', 'wimp', 'whiny', 'worsening', 'worst',
        'confused', 'confusing', 'confusion', 'frenzied', 'frenzy', 'resigned', 'pleading', 'quarrel',
        'reckless', 'relapse', 'relapsing', 'remission', 'pauper', 'penniless', 'vagabond', 'vagrancy',
        'vagrantly', 'abridge',
        // religion, race and politics
        'agnostic', 'almighty', 'apostle', 'blaspheme', 'blasphemy', 'buddhism', 'buddhist', 'cathedral',
        'caucasian', 'chaplain', 'clergyman', 'convent', 'darwinism', 'deacon', 'deity', 'democrat',
        'diocese', 'divinely', 'divinity', 'eskimo', 'fascism', 'gentile', 'islamic', 'islamist',
        'marxism', 'monastery', 'monkhood', 'pagan', 'parish', 'passover', 'pastor', 'pope', 'prayer',
        'praying', 'preachy', 'president', 'purgatory', 'racism', 'race', 'reverend', 'sacrament',
        'sacred', 'saint', 'salvation', 'sanctity', 'sanctuary', 'senate', 'senator', 'sermon', 'siamese',
        'sinless', 'supremacy', 'theology', 'trinity', 'yiddish', 'congress',
        // Greek letters: a key must never read like a chapter name
        'alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'kappa', 'lambda',
        'omicron', 'rho', 'sigma', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega',
    ],

    'exact' => [
        'die', 'died', 'dies', 'dying', 'war', 'warfare', 'warlord', 'warpath', 'hit', 'hits',
        'butt', 'butts', 'bra', 'nun', 'gay', 'kin', 'pet', 'pets', 'petting', 'cut', 'cuts',
        'cutting', 'stab', 'shot', 'shots', 'rob', 'robs', 'lie', 'lied', 'lies', 'sad', 'sadly',
        'sadness', 'hurt', 'harm', 'harmful', 'ill', 'pain', 'raw', 'rawness', 'wet', 'moist',
        'sticky', 'slimy', 'hot', 'hottie', 'steamy', 'sultry', 'tight', 'loose', 'rough', 'hard',
        'harden', 'firm', 'stiff', 'limp', 'thrust', 'pump', 'ride', 'rider', 'riding', 'mount',
        'straddle', 'spread', 'open', 'opened', 'enter', 'entry', 'push', 'pushy', 'pull', 'tug',
        'grip', 'grasp', 'clutch', 'hold', 'held', 'pin', 'pins', 'nail', 'screw', 'screwed', 'bang',
        'bump', 'pop', 'popped', 'blow', 'blown', 'suck', 'sucker', 'come', 'came', 'coming',
        'dirt', 'mess', 'messy', 'stain', 'stained', 'smear', 'smudge', 'scum', 'slime', 'sludge',
        'trash', 'garbage', 'rubbish', 'junk', 'waste', 'wasted', 'used', 'user', 'abuse', 'cheap',
        'easy', 'tease', 'flaunt', 'tramp', 'tart', 'vixen', 'harlot', 'hussy', 'wench', 'floozy',
        'pimp', 'john', 'trick', 'trade', 'cash', 'pay', 'paid', 'owe', 'owed', 'debt', 'deal',
        'hunk', 'stud', 'macho', 'manly', 'male', 'female', 'woman', 'women', 'man', 'men', 'girl',
        'girls', 'boy', 'boys', 'guy', 'guys', 'lad', 'lass', 'son', 'daughter', 'mother', 'father',
        'mom', 'dad', 'uncle', 'aunt', 'cousin', 'nephew', 'niece', 'brother', 'sister', 'sibling',
        'coach', 'teacher', 'tutor', 'mentor', 'boss', 'manager', 'officer', 'guard', 'stranger',
        'friend', 'buddy', 'pal', 'roommate', 'neighbor', 'player', 'athlete', 'team', 'captain',
        'student', 'pupil', 'dean', 'professor', 'staff', 'faculty', 'employee', 'employer',
        'drunken', 'tipsy', 'buzzed', 'high', 'stone', 'weed', 'pot', 'joint', 'hash', 'smoke',
        'smoking', 'shots', 'keg', 'brew', 'rum', 'gin', 'ale', 'lager', 'stout', 'cider', 'punch',
        'shook', 'shiver', 'chill', 'chilly', 'cold', 'numbly', 'blank', 'empty', 'void', 'hollow',
        'gone', 'lost', 'loss', 'missing', 'vanish', 'forget', 'forgot', 'forgotten', 'blur', 'blurry',
        'foggy', 'haze', 'hazy', 'fog', 'murky', 'dim', 'shadow', 'shady', 'gloomy', 'bleak',
    ],
];
