-- One page per state and DC. Every row starts as needs_legal_review with no
-- legal text; the public page then shows "Information coming soon" and the
-- national hotline only. Legal fields are filled in, and the status set to
-- published, by an admin after legal review. Nothing here was invented.
CREATE TABLE IF NOT EXISTS state_pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code CHAR(2) NOT NULL,
    name VARCHAR(60) NOT NULL,
    status ENUM('needs_legal_review', 'published') NOT NULL DEFAULT 'needs_legal_review',
    statute_of_limitations MEDIUMTEXT NULL,
    resources MEDIUMTEXT NULL,
    legal_reviewed_by VARCHAR(255) NULL,
    legal_reviewed_on DATE NULL,
    updated_by INT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_code (code),
    CONSTRAINT fk_state_pages_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO state_pages (code, name, status) VALUES
('AL', 'Alabama', 'needs_legal_review'),
('AK', 'Alaska', 'needs_legal_review'),
('AZ', 'Arizona', 'needs_legal_review'),
('AR', 'Arkansas', 'needs_legal_review'),
('CA', 'California', 'needs_legal_review'),
('CO', 'Colorado', 'needs_legal_review'),
('CT', 'Connecticut', 'needs_legal_review'),
('DE', 'Delaware', 'needs_legal_review'),
('DC', 'District of Columbia', 'needs_legal_review'),
('FL', 'Florida', 'needs_legal_review'),
('GA', 'Georgia', 'needs_legal_review'),
('HI', 'Hawaii', 'needs_legal_review'),
('ID', 'Idaho', 'needs_legal_review'),
('IL', 'Illinois', 'needs_legal_review'),
('IN', 'Indiana', 'needs_legal_review'),
('IA', 'Iowa', 'needs_legal_review'),
('KS', 'Kansas', 'needs_legal_review'),
('KY', 'Kentucky', 'needs_legal_review'),
('LA', 'Louisiana', 'needs_legal_review'),
('ME', 'Maine', 'needs_legal_review'),
('MD', 'Maryland', 'needs_legal_review'),
('MA', 'Massachusetts', 'needs_legal_review'),
('MI', 'Michigan', 'needs_legal_review'),
('MN', 'Minnesota', 'needs_legal_review'),
('MS', 'Mississippi', 'needs_legal_review'),
('MO', 'Missouri', 'needs_legal_review'),
('MT', 'Montana', 'needs_legal_review'),
('NE', 'Nebraska', 'needs_legal_review'),
('NV', 'Nevada', 'needs_legal_review'),
('NH', 'New Hampshire', 'needs_legal_review'),
('NJ', 'New Jersey', 'needs_legal_review'),
('NM', 'New Mexico', 'needs_legal_review'),
('NY', 'New York', 'needs_legal_review'),
('NC', 'North Carolina', 'needs_legal_review'),
('ND', 'North Dakota', 'needs_legal_review'),
('OH', 'Ohio', 'needs_legal_review'),
('OK', 'Oklahoma', 'needs_legal_review'),
('OR', 'Oregon', 'needs_legal_review'),
('PA', 'Pennsylvania', 'needs_legal_review'),
('RI', 'Rhode Island', 'needs_legal_review'),
('SC', 'South Carolina', 'needs_legal_review'),
('SD', 'South Dakota', 'needs_legal_review'),
('TN', 'Tennessee', 'needs_legal_review'),
('TX', 'Texas', 'needs_legal_review'),
('UT', 'Utah', 'needs_legal_review'),
('VT', 'Vermont', 'needs_legal_review'),
('VA', 'Virginia', 'needs_legal_review'),
('WA', 'Washington', 'needs_legal_review'),
('WV', 'West Virginia', 'needs_legal_review'),
('WI', 'Wisconsin', 'needs_legal_review'),
('WY', 'Wyoming', 'needs_legal_review');
